apiVersion: argyle.com/v1
kind: KSOPSGenerator
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
fail-silently: false
spec:
  files:
  - ./secret.enc.yaml
