apiVersion: argyle.com/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |2-
      exec:
        path: ksops
fail-silently: false
files:
- ./secret.enc.yaml
