version: 2

updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  rebase-strategy: disabled

- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  rebase-strategy: disabled
