project_name: argyle-kops
env:
  - GO111MODULE=on
builds:
  - id: ksops-darwin-amd64
    binary: ksops
    env:
      - CGO_ENABLED=0
    main: ./cmd/ksops/main.go
    goos:
      - darwin
    goarch:
      - amd64

  - id: ksops-darwin-arm64
    binary: ksops
    env:
      - CGO_ENABLED=0
    main: ./cmd/ksops/main.go
    goos:
      - darwin
    goarch:
      - arm64


  - id: ksops-linux
    binary: ksops
    env:
      - CGO_ENABLED=0
    main: ./cmd/ksops/main.go
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz
    name_template: "{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      amd64: x64
      arm64: ARM64
      darwin: macOS
      linux: Linux
    allow_different_binary_count: true

sboms:
  - artifacts: binary

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}
