name: fmt

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - run: go fmt ./...

    - name: Commit fmt changes
      uses: EndBug/add-and-commit@v9.1.2
      with:
        add: '*'
        author_name: root
        author_email: argyle-ksops@argyle.io
        message: 'Running fmt'
